# Generated by Django 4.1.3 on 2023-01-03 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_friends_friendrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed', to=settings.AUTH_USER_MODEL)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
