# Generated by Django 4.1.3 on 2023-02-22 13:51

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0012_rename_comment_comments_text_comments_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observed',
            new_name='Observers',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
