# Generated by Django 4.1.3 on 2023-02-22 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0013_rename_observed_observers_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observers',
            new_name='Observer',
        ),
    ]
